name: buildx

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Build base
        run: |
          docker build -f Dockerfile.base -t exfly/netshoot:base .
      -
        name: Run Buildx
        run: |
          docker build -t exfly/netshoot:dev .
      - name: save docker images
        run: |
          docker save --output netshoot.tar exfly/netshoot:dev
      - name: Archive docker images artifacts
        uses: actions/upload-artifact@v2
        with:
          name: prod-shoot-image
          path: |
            netshoot.tar
